{% set data = load_setup_py_data() %}

package:
    name: ibis-singlestoredb
    version: {{ data.get('version') }}

source:
    path: ..

build:
    noarch: python
    number: {{ environ.get('PACKAGE_BUILD_NUMBER', '0') }}
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python {{ python }}
        - pip
    run:
        - singlestoredb
        - sqlalchemy-singlestoredb
        - ibis-framework

test:
    imports:
        - ibis_singlestore
    requires:
        - coverage
        - pandas
        - pytest
        - pytest-cov
    commands:
        - pytest -v ibis_singlestoredb.tests

about:
    home: https://github.com/singlestore-labs/ibis-singlestore
    license: Apache 2.0
    license_file: ../LICENSE
    summary: SingleStoreDB SQLAlchemy Dialect
    doc_url: https://singlestore.github.io/ibis-singlestoredb/index.html
    dev_url: https://github.com/singlestore/ibis-singlestoredb
