name: Coverage tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    services:
      singlestore:
        image: ghcr.io/singlestore-labs/singlestoredb-dev:latest
        ports:
          - 3306:3306
          - 8080:8080
          - 9000:9000
        env:
          SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}
          ROOT_PASSWORD: "root"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Install SingleStoreDB Ibis backend
        run: |
          python setup.py install

      - name: Install test database
        run: |
          python resources/init_db.py -h 127.0.0.1 -P 3306 -u root --password root -d ibis_testing ibis_singlestoredb/tests/test.sql

      - name: Run MySQL protocol tests
        run: |
          pytest -q --cov=ibis_singlestoredb ibis_singlestoredb/tests
        env:
          COVERAGE_FILE: "coverage-mysql.cov"
          IBIS_TEST_SINGLESTOREDB_ROOT_USER: "root"
          IBIS_TEST_SINGLESTOREDB_ROOT_PASSWORD: "root"
          IBIS_TEST_SINGLESTOREDB_USER: "root"
          IBIS_TEST_SINGLESTOREDB_PASSWORD: "root"
          IBIS_TEST_SINGLESTOREDB_DRIVER: "mysql"
          IBIS_TEST_SINGLESTOREDB_HOST: "127.0.0.1"
          IBIS_TEST_SINGLESTOREDB_PORT: "3306"
          IBIS_TEST_SINGLESTOREDB_DATABASE: "ibis_testing"
          SINGLESTOREDB_URL: "root:root@127.0.0.1:3306/ibis_testing"
          SINGLESTOREDB_MANAGEMENT_TOKEN: ${{ secrets.CLUSTER_API_KEY }}

      - name: Run HTTP protocol tests
        run: |
          pytest -q --cov=ibis_singlestoredb ibis_singlestoredb/tests
        env:
          COVERAGE_FILE: "coverage-http.cov"
          IBIS_TEST_SINGLESTOREDB_ROOT_USER: "root"
          IBIS_TEST_SINGLESTOREDB_ROOT_PASSWORD: "root"
          IBIS_TEST_SINGLESTOREDB_USER: "root"
          IBIS_TEST_SINGLESTOREDB_PASSWORD: "root"
          IBIS_TEST_SINGLESTOREDB_DRIVER: "http"
          IBIS_TEST_SINGLESTOREDB_HOST: "127.0.0.1"
          IBIS_TEST_SINGLESTOREDB_PORT: "9000"
          IBIS_TEST_SINGLESTOREDB_DATABASE: "ibis_testing"
          SINGLESTOREDB_URL: "http://root:root@127.0.0.1:9000/ibis_testing"
          SINGLESTOREDB_MANAGEMENT_TOKEN: ${{ secrets.CLUSTER_API_KEY }}

      - name: Generate report
        run: |
          coverage combine coverage-mysql.cov coverage-http.cov
          coverage report
          coverage xml
          coverage html
